### PR TITLE
Make exception for plugins when checking for name uniqueness

### LINKED ISSUE #294: Model::Load should not emit duplicate child element warning for <plugin> elements
`<plugin>` elements should be ignored when validating a model for name uniqueness, but `Model::Load` emits a warning if it encounters multiple `<plugin>` elements with the same name attribute.

Related: ignitionrobotics/ign-gazebo#164

### LINKED ISSUE #712: InspectSDFElement should allow duplicate plugin names
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
Binary: 9.6.1

## Description
* Expected behavior: Have multiple child elements with the same name should not produce an error if the element type is "plugin"
* Actual behavior:
If an element in the SDF contains multiple child plugin elements with the same name:
* The `recursiveSameTypeUniqueNames` function and the `recursiveSiblingUniqueNames` function in `parser.cc` (called by Gazebo) output an error message containing the entire element followed by the message 
```
[Err] [Server.cc:98] SDF is not valid, see errors above. This can lead to an unexpected behaviour.
```
Model.cc also produces a warning: 
```
Warning [Model.cc:212] Non-unique names detected in XML children of model with name[element_name]
```
## Steps to reproduce

1. Define a model with a plugin in the definition. For example we have a buoy model (https://github.com/osrf/vrx/blob/master/vrx_gazebo/models/mb_marker_buoy_red/model.sdf) that uses an attached bouyancy plugin.  
2. Define a nested model that uses several instances of the model you defined the previous step. For example, we have a nested model that arranges several of these buoys into a [navigation course](https://github.com/osrf/vrx/blob/master/vrx_gazebo/models/navigation_course0/model.sdf). 
3. Launch Gazebo using a world that has the nested model in it.

## Output
Using a version of the example above with only two buoys, we see:
```
Error: Non-unique names detected in type plugin in
<model name='short_navigation_course_0'>
  <frame name='red_bound_0::__model__' attached_to='red_bound_0::link'>
    <pose relative_to='__model__'>0 0 0 0 -0 0</pose>
  </frame>
  <link name='red_bound_0::link'>
    <inertial>
      <pose>0 0 -2 0 -0 0</pose>
      <mass>20</mass>
      <inertia>
        <ixx>1</ixx>
        <ixy>0</ixy>
        <ixz>0</ixz>
        <iyy>1</iyy>
        <iyz>0</iyz>
        <izz>0.1</izz>
      </inertia>
    </inertial>
    <collision name='collision_inner'>
      <pose>0 -0.02 0.02 0 -0 0</pose>
      <geometry>
        <cylinder>
          <radius>0.15</radius>
          <length>1.15</length>
        </cylinder>
      </geometry>
    </collision>
    <collision name='collision_outer'>
      <pose>0 0 -0.3 0 -0 0</pose>
      <geometry>
        <cylinder>
          <radius>0.325</radius>
          <length>0.1</length>
        </cylinder>
      </geometry>
    </collision>
    <visual name='visual'>
      <pose>0 0 0 1.57079 -0 0</pose>
      <geometry>
        <mesh>
          <uri>model://mb_marker_buoy_red/meshes/mb_marker_buoy.dae</uri>
        </mesh>
      </geometry>
      <material>
        <script>
          <uri>model://mb_marker_buoy_red/materials/scripts/mb_marker_buoy.material</uri>
          <name>mb_marker_buoy/Red</name>
        </script>
      </material>
    </visual>
    <pose relative_to='red_bound_0::__model__'>0 0 0 0 -0 0</pose>
  </link>
  <plugin name='BuoyancyPlugin' filename='libbuoyancy_gazebo_plugin.so'>
    <wave_model>ocean_waves</wave_model>
    <fluid_density>1000</fluid_density>
    <fluid_level>0.0</fluid_level>
    <linear_drag>25.0</linear_drag>
    <angular_drag>2.0</angular_drag>
    <buoyancy name='buoyancy_sphere'>
      <link_name>red_bound_0::link</link_name>
      <pose>0 0 -0.12 0 0 0</pose>
      <geometry>
        <sphere>
          <radius>0.325</radius>
        </sphere>
      </geometry>
    </buoyancy>
  </plugin>
  <frame name='green_bound_0::__model__' attached_to='green_bound_0::link'>
    <pose relative_to='__model__'>0 -20 0.2 0 -0 0</pose>
  </frame>
  <link name='green_bound_0::link'>
    <inertial>
      <pose>0 0 -2 0 -0 0</pose>
      <mass>20</mass>
      <inertia>
        <ixx>1</ixx>
        <ixy>0</ixy>
        <ixz>0</ixz>
        <iyy>1</iyy>
        <iyz>0</iyz>
        <izz>0.1</izz>
      </inertia>
    </inertial>
    <collision name='collision_inner'>
      <pose>0 -0.02 0.02 0 -0 0</pose>
      <geometry>
        <cylinder>
          <radius>0.15</radius>
          <length>1.15</length>
        </cylinder>
      </geometry>
    </collision>
    <collision name='collision_outer'>
      <pose>0 0 -0.3 0 -0 0</pose>
      <geometry>
        <cylinder>
          <radius>0.325</radius>
          <length>0.1</length>
        </cylinder>
      </geometry>
    </collision>
    <visual name='visual'>
      <pose>0 0 0 1.57079 -0 0</pose>
      <geometry>
        <mesh>
          <uri>model://mb_marker_buoy_red/meshes/mb_marker_buoy.dae</uri>
        </mesh>
      </geometry>
      <material>
        <script>
          <uri>file://media/materials/scripts/gazebo.material</uri>
          <name>Gazebo/White</name>
        </script>
      </material>
    </visual>
    <pose relative_to='green_bound_0::__model__'>0 0 0 0 -0 0</pose>
  </link>
  <plugin name='BuoyancyPlugin' filename='libbuoyancy_gazebo_plugin.so'>
    <wave_model>ocean_waves</wave_model>
    <fluid_density>1000</fluid_density>
    <fluid_level>0.0</fluid_level>
    <linear_drag>25.0</linear_drag>
    <angular_drag>2.0</angular_drag>
    <buoyancy name='buoyancy_sphere'>
      <link_name>green_bound_0::link</link_name>
      <pose>0 0 -0.12 0 0 0</pose>
      <geometry>
        <sphere>
          <radius>0.325</radius>
        </sphere>
      </geometry>
    </buoyancy>
  </plugin>
  <pose>-475 185 0 0 0 -2.14</pose>
</model>

[Err] [Server.cc:98] SDF is not valid, see errors above. This can lead to an unexpected behaviour.
Warning [Model.cc:212] Non-unique names detected in XML children of model with name[short_navigation_course_0].
```

## Additional Notes
I haven't yet found documentation confirming that duplicate plugin names are allowed, but [the comment on line 1476 of `parser.cc` in `sdformat`](https://github.com/ignitionrobotics/sdformat/blob/sdf11/src/parser.cc) suggests this is the case.

Additionally, the sdformat implementation of the `<include>` tag does not rename plugins to avoid name conflicts, as it does with other elements, and plugin names also can't be overridden when a model is invoked. As illustrated in the above example, this means that whenever a model definition includes a plugin and that model is used more than once in a nested model, Gazebo will report that the SDF is invalid.

### PR DESCRIPTION
**Pull request by azeey**
# 🦟 Bug fix

Fixes #712 
Fixes #294

## Summary
As discussed in #712, #294 and possibly other issues, the `name` attribute of `<plugin>` is used by downstream applications like ign-gazebo to specify the class name within the plugin, so name collisions can occur frequently. This PR adds an exception for the `<plugin>` so that no warning is emitted when a plugin name matches the names of other entities.

I've added overloads to functions in  `sdf::Element` so that this PR can be backported to `sdf9`.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

File: include/sdf/Element.hh [hunk 1]
```diff
@@ -532,6 +560,11 @@ namespace sdf
     /// \return A pointer to the named element if found, nullptr otherwise.
     public: ElementPtr GetElementImpl(const std::string &_name) const;
 
+    /// \brief List of elements to which exceptions are made when checking for
+    /// name uniqueness.
+    /// \return List of element types that are allowed to name collisions.
```
Comment (scpeters) [inline include/sdf/Element.hh:565]: missing a verb? "allowed to *have* name collisions"?

**Review by scpeters — COMMENTED** [review]
just one minor nit about wording of documentation

looks good otherwise

File: include/sdf/Element.hh (hunk 1 above)
Comment (azeey) [reply include/sdf/Element.hh]: https://github.com/ignitionrobotics/sdformat/pull/721/commits/c8935c1f653c602b6969ea99dd49abde1b5d4d18

**Review by scpeters — APPROVED** [review]
