### PR TITLE
Fix loading nested include with custom attributes

### LINKED ISSUE #502: Should test custom elements via composition for emitted SDFormat strings (round trip)

### PR DESCRIPTION
**Pull request by jennuine**
# 🦟 Bug fix

Closes #502

## Summary
When working on tests for #502 , I found a bug with nested includes where the included file contained custom attributes. In the parser's `addNestedModel` call,  after the string replacement for flattening, the `_includeSDF` element was cleared but not it's attributes. This resulted in the custom attribute being added twice and the duplicate attribute would be left with an empty value. This PR fixes the issue by clearing the attributes before calling `readString` and adds tests to ensure custom elements/attributes are preserved when loading a sdformat file and reloading the string output.

**Before PR**
Check out this PR and comment out `_includeSDF->RemoveAllAttributes()` from:
https://github.com/ignitionrobotics/sdformat/blob/1c6c0a55d07cc75057f8cc44c5a25b85f155ee8e/src/parser.cc#L1375-L1377

Then run:
```bash
./path/to/build/test/integration/INTEGRATION_sdf_custom --gtest_filter=SDFParser.ReloadNestedIncludedCustomElements
```

The error is:
```bash
Required attribute[xmlns:mysim] in element[sdf] is not specified in SDF.
```

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: test/integration/sdf_custom.cc [hunk 1]
```diff
@@ -82,3 +82,222 @@ TEST(SDFParser, CustomElements)
...
+  ASSERT_NE(nullptr, customElem1);
+  ASSERT_NE(nullptr, customElem2);
+  EXPECT_EQ(customElem1->ToString(""), customElem2->ToString(""));
+  sdf::ElementPtr customDesc1 =
+      world1->Element()->FindElement("mysim:description");
+  sdf::ElementPtr customDesc2 =
+      world2->Element()->FindElement("mysim:description");
+  ASSERT_NE(nullptr, customDesc1);
+  ASSERT_NE(nullptr, customDesc2);
+  EXPECT_EQ(customDesc1->ToString(""), customDesc2->ToString(""));
```
Comment (azeey) [inline test/integration/sdf_custom.cc:133]: Can we compare the result of `customDesc2->ToString` with the expected string literal instead of trusting `customDesc1->ToString` is working properly? Here and below. Not to make to verbose, I would only do it on the comparisons that involve custom elements.

**Review by azeey — APPROVED** [review]

File: test/integration/sdf_custom.cc (hunk 1 above)
Comment (jennuine) [reply test/integration/sdf_custom.cc]: c54dccb0f328c0f7e1f00339ed0d740f963faddd

**Review by azeey — APPROVED** [review]

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-10/1228/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-25-fortress-edifice-citadel/1343/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1
