### PR TITLE
Fix segfault when checking for required elements in joint

### LINKED ISSUE #590: Segfault when parsing incorrect SDF.
`elemXml`  may be undefined on this line since the loop prior to it terminates on it being `nullptr`:

https://github.com/osrf/sdformat/blob/85ebd9ba6774d1cdc89f9f03ab98da4d43267442/src/parser.cc#L1502

### PR DESCRIPTION
**Pull request by aaronchongth**
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

# 🦟 Bug fix

Fixes #590 

## Summary

* Switched to using `xml->GetLineNum()` instead of `elemXml->GetLineNum()`
* Added test for this particular error.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

File: src/parser_TEST.cc [hunk 1]
```diff
@@ -767,6 +767,52 @@ TEST(Parser, ElementFilePath)
...
+      </world>
+    </sdf>)";
+
+  auto findFileCb = [](const std::string &_uri)
+  {
+    return sdf::testing::TestFile("integration", "model", _uri);
+  };
+
+  sdf::ParserConfig config;
+  config.SetFindCallback(findFileCb);
```
Comment (azeey) [inline src/parser_TEST.cc:800]: nit: Since there are no `//include` elements, is the `findFileCb` needed?

**Review by azeey — APPROVED** [review]

File: src/parser_TEST.cc (hunk 1 above)
Comment (aaronchongth) [reply src/parser_TEST.cc]: Thanks for catching that, removed in https://github.com/ignitionrobotics/sdformat/pull/610/commits/1c79f2fd80f84b801ce5d490ed9f764379805096
